version: "3.7"

services:
  kayanhr-mongo:
    container_name: kayanhr-mongo
    image: mongo:4
    restart: always
    volumes:
      - /data/kayanhr-website/db:/data/db
    expose:
      - "27017"
    networks:
      - kayanhr

  kayanhr-mongo-express:
    container_name: kayanhr-mongo-express
    image: mongo-express:0.54.0
    restart: always
    environment:
      - "ME_CONFIG_MONGODB_SERVER=kayanhr-mongo"
      - "ME_CONFIG_BASICAUTH_USERNAME=root"
      - "ME_CONFIG_BASICAUTH_PASSWORD=wtmMONGO022"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.kayanhr-mongo.entrypoints=http"
      - "traefik.http.routers.kayanhr-mongo.rule=Host(`mongo.kayanhr.local.wtmsrv.com`)"
      - "traefik.http.routers.kayanhr-mongo.middlewares=redirect@file"
      - "traefik.http.routers.kayanhr-mongo-secure.entrypoints=https"
      - "traefik.http.routers.kayanhr-mongo-secure.rule=Host(`mongo.kayanhr.local.wtmsrv.com`)"
      - "traefik.http.routers.kayanhr-mongo-secure.tls=true"
      - "traefik.http.routers.kayanhr-mongo-secure.service=kayanhr-mongo-secure"
      - "traefik.http.routers.kayanhr-mongo-secure.tls.certresolver=wtmtlschallenge"
      - "traefik.http.services.kayanhr-mongo-secure.loadbalancer.server.port=8081"
    depends_on:
      - kayanhr-mongo
    networks:
      - kayanhr
      - traefik

networks:
  kayanhr:
    name: kayanhr
  traefik:
    external: true
